CREATE TYPE location_type AS ENUM (
    'Restaurant',
    'Food Bank',
    'School',
    'Other Non-Profit'
);

CREATE TABLE locations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    location_name TEXT NOT NULL,
    street_address TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    zip INTEGER,
    open_hour TIME,
    close_hour TIME,
    website TEXT,
    location_description TEXT,
    location_type location_type
);

CREATE TABLE comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    location_id INTEGER REFERENCES locations(id) ON DELETE CASCADE NOT NULL,
    comment_text TEXT NOT NULL,
    has_concern BOOLEAN
);

CREATE TABLE tags (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tag_name TEXT NOT NULL
);

CREATE TABLE tag_relations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tag_id INTEGER REFERENCES tags(id) ON DELETE CASCADE NOT NULL,
    location_id INTEGER REFERENCES locations(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE operating_days (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    operating_day TEXT NOT NULL
);

CREATE TABLE operating_days_relations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    day_id INTEGER REFERENCES operating_days(id) ON DELETE CASCADE NOT NULL,
    location_id INTEGER REFERENCES locations(id) ON DELETE CASCADE NOT NULL
);